# Generated by Django 4.2.7 on 2023-12-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovosDados',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('senha', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
