# Generated by Django 4.2.7 on 2023-11-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
